pgpKeySign: 33B2 D900 0DC9 C4EB EA99 CAE7 64C4 AB4F DCA2 F4B5
pgpRelPath: pgp.key

bornBC: 21.104 years

jobTitle: Software Engineer
jobFirm: Knowbe4
jobFirmUrl: https://www.knowbe4.com/?ref=brutt.site

spotifyProfile: https://open.spotify.com/user/31nfl5znljrwp4r5v4a3pcingxam

contacts:
  email: mailto:agrajpdas@gmail.com
  matrix: https://matrix.to/#/@bruttazz:matrix.org
  mastodon: https://fosstodon.org/@bRuttaZz
  github: https://github.com/bruttazz
  linkedin: https://www.linkedin.com/in/agraj-p-das
  instagram: https://www.instagram.com/bRuttaZz
