title: "Teachers: A Lazy Love Letter"
tag: scribble
shortDescription: A lazy scribble on teachers. Wrote out of inspiration from the movie Klaus.
longDescription:
  Lazy scribble. Humans share! What else might expand our horizon of knowledge
  and wisdom if there were no teachers? Saw a passionate teacher being portrayed in the movie Klaus.
keyWords:
  - humanity
  - knowledge
  - student
  - teacher
shareImage: https://brutt.site/assets/blogs/13.note-on-teachers/klaus-alva-teacher.jpg
# optional fields
# last edit overide in YYYY/MM/DD fmt (if not provided will using git commit)
# lastEdit: 2001/10/28
