title: "Good thing is: Life is not a univariate function of time, or is it?"
shortDescription: Just a super simplified yet reasonable proof that Laplace's
  demon can not be real.
longDescription: Just a super simplified yet reasonable proof that Laplace's
  demon can not be real.
keyWords:
  - laplace-demon
  - demon
  - daemon
  - laplace-deamon
  - life
  - time
  - lifeandtime
  - thermodynamics
  - heat
  - life
  - information theory
  - information
  - randomness
  - entropy
  - second law
shareImage: https://brutt.site/assets/blogs/11.life-is-no-a-function-of-time/laplace-deamon.jpg

# override
lastEdit: "2025/02/26"
