title: ~/.Secret_Prayers
tag: scribble
shortDescription: Archived late night notes on humanity's warm bias for longing.
longDescription: Archived late night notes on humanity's warm bias for longing.
keyWords:
  - poem
  - scribble
  - girl
  - love
  - longing
shareImage: https://brutt.site/assets/blogs/14.secret-prayers/his-desk.jpg

# lastEdit overwride if not provided will using git commit
lastEdit: 2025/05/26
